### ISSUE TITLE
Problem with symlinks over Vagrant shared folders

### ISSUE THREAD

**Issue by philbates35** [Letudiant/composer-shared-package-plugin#1]
Just trying to get this set up and I've come across a problem with the symlinks.

I use Vagrant with NFS shared folders as my development environment. My local folder structure is:

```
~ 
---- code
--------www
------------project1
------------project2
--------packages (your plugin's vendor-dir where the packages are downloaded to)
------------mycompany
----------------mycompanypackage1
----------------mycompanypackage2
```

I have the following Vagrant shared folders:

```
~/code/www --> /home/www
```
```
~/code/packages --> /home/packages
```

Meaning the folder structure on my VM is very similar to local, but ever so slightly different:

```
home
----www
--------project1
--------project2
----packages (your plugin's vendor-dir where the packages are downloaded to)
--------mycompany
------------mycompanypackage1
------------mycompanypackage2
```

In my project root I have:

```
"shared-package": {
    "vendor-dir": "../../packages"
}
```

Although the local and VM folder hierarchy is slightly different, the relative vendor-dir I provided is perfectly valid for both my VM and local directory structures.

The problem is with the symlink that is created:

```
www/projectroot/venor-shared/mycompany/package1 -> /home/packages/mycompany/package1/dev-default/
```

On the VM this is a valid symlink. However, on my local the symlink is seen as broken as the target doesn't exist (`/home/packages/mycompany/package1/dev-default/` which is a valid directory on the VM doesn't exist on the local filesystem, and should instead be `~/code/packages/mycompany/package1/dev-default/`). This means locally, PhpStorm and the filesystem thinks the link is broken and I can't click through to the package.

The solution would be to generate the symlink relative to the vendor-shared folder:
```
project1/vendor-shared/mycompany/package1 -> ../../../../../packages/mycompany/package1/dev-default/
```

I imagine I'm not the only person using Vagrant shared folders with slightly different directory structures on VM and local, and I think this would cause issues for everyone with that set up. Can you think of a way that the symlink that is generated could be relative to the vendor-shared directory rather than absolute?

Happy to provide more explanation or information if required.

Thanks.

**Comment by Divi** [comment]
Hey @philbates35 

I use this plugin with Vagrant too, but with a synced_folder as `vendor-dir`.  
The relative path for symlink is not a bad idea, but I'm afraid that Composer has some issues with relative symlink, but I'll try it.

Thanks :+1:

**Comment by philbates35** [comment]
No problem, let me know if you find a solution. Of course implementing a relative symlink doesn't have to be the solution, it just seemed the most obvious answer to me when I quickly tried to think of how this could be solved.

You mentioned that you use a Vagrant synced folder as your vendor-dir. That's exactly what I was doing - my `packages` folder was shared over Vagrant, but the problem was that the location of the `packages` folder was different in the VM (`/home/packages`) compared to local (`~/code/packages`). Composer ran in the VM, and created the absolute symlink to the location of the `packages` folder in the VM, which is invalid locally. Would I be right in assuming that your vendor-dir's location is identical on both your VM and local? e.g `/home/packages` on local and `home/packages` on VM. That's the only was I can think that you were able to get it to work.

**Comment by Divi** [comment]
Yes it is, I edited my answer just after posting it : 

> which is the same as my guest machine

I think the best way is to implement a configuration to override the symlink path, like :

``` json
// composer.json (project)
{
    "extra": {
        "shared-package": {
            "vendor-dir": "../../packages",
            "symlink-path": "~/code/packages"
        }
    }
}
```

Indeed, symlinks only exist to be a shortcut to packages sources for the IDE. The autoloader targets the VM packages path (`vendor-dir`).

**Comment by philbates35** [comment]
Ah yes you edited before I started writing my response. Thanks for clearing that up.

Just to check I understand: you're saying that if the file structures were different between local and VM, I could add a symlink-path configuration option (that is yet to be implemented) that would explicitly point to the vendor-dir from the perspective of my local file system. I would then end up with a working symlink locally (so PhpStorm could read into it), but a broken symlink in the VM. However, the broken symlink in the VM isn't actually a problem at all, because the composer autoloader running inside the VM never even uses the symlink and targets the vendor-dir directly.

If that's the case then I think that would be an okay solution. It seems a little messy having a broken symlink remaining on the VM, but I can't think of a better solution.

**Comment by Divi** [comment]
Exactly ! :+1: 

I don't think that having a broken symlink in VM is wrong because this plugin should improve your dev workflow. Moreover, you should not use the symlink path in your sources because when you'll create a tagged version for production, the package will go in `vendor` file, as the default behavior, and the `vendor-shared` directory won't be created.

**Comment by Divi** [comment]
Hey @philbates35, I create the configuration `symlink-base-path`.

You must update your project `composer.json` with this require : 

``` json
{
    "require": {
        "letudiant/composer-shared-package-plugin": "1.1.*@dev"
    },
    "extra": {
        "shared-package": {
            "symlink-base-path": "~/code/packages"
        }
    }
}
```
*(check if I'm not wrong with the path)*
Then run a `composer update "letudiant/composer-shared-package-plugin"`.

Please, let a feedback :smiley:

**Comment by philbates35** [comment]
Hi @Divi thanks for getting back to me. I've had a play around and here's what I've found.

I didn't realise (until I just Googled it because it wasn't working), but apparently it isn't possible to use `~` in a symlink. Which means that using `"~/code/packages"` as the `symlink-base-path` resulted in a broken symlink. Not your problem of course!

I was able get it working by explicitly stating the full directory path rather than using `~`:

```
"shared-package": {
    "symlink-base-path": "/home/philbates35/code/packages"
}
```

However that isn't a practical solution as the resulting `composer.json` will be committed to VCS and shared across the team - my home directory will be hard coded causing it to break for everyone else.

The only solution I found that is dynamic enough to share across the team was to specify a relative symlink that traversed up the filesystem:

```
"shared-package": {
    "symlink-base-path": "../../../../packages"
}
```

It had to go up four levels because the symlink path is relative to the actual symlink in the vendor-shared directory: Two levels to get to `composer.json`'s directory, then one level to the web root, and finally one last level to get out of the web root (the package's directory I want as the symlink base path is on the same level as the web root directory)

I personally think that it would be better and be less confusing if the `symlink-base-path` was relative to the directory that `composer.json` sits in. Behind the scenes you could check if a relative symlink has been provided; if it has, then assume it is relative to the `composer.json` directory and manually prepend `../../` to the provided relative path to get out of the vendor-shared directory.

To clarify, I would like the following directory structure:

```
code
----packages
--------mycompanyvendor
------------package1
----------------dev-default
----------------dev-default
------------package2
----www
--------project1
------------vendor
------------vendor-shared
----------------mycompanyvendor
--------------------package1 -> ../../../../packages/mycompanyvendor/package1/dev-default
--------------------package2 -> ../../../../packages/mycompanyvendor/package2/dev-default
------------composer.json
```

And ideally I would like to specify the following in `composer.json`:

```
"shared-package": {
    "symlink-base-path": "../../packages",
    "vendor-dir": "../../packages"
}
```

I'm not sure how you feel about having the same path duplicated twice in the `compser.json` configuration though, it seems a little unneccessary in this case.

Let me know your thoughts!

**Comment by Divi** [comment]
Hmm, for your case, indeed, the `symlink-base-path` seems to be useless.

> The only solution I found that is dynamic enough to share across the team was to specify a relative symlink that traversed up the filesystem

I think is the best idea indeed, I'll detect if the `vendor-dir` is relative, if it is, the symlink base path will be automatically prepend with relative path and the `vendor-dir` path is still absolute.

So, it will be :

``` json
"shared-package": {
    "vendor-dir": "../../packages"
}
```

Internal :
``` php
$vendorDir = '/absolute/path/to/packages';
$symlinkBasePath = '../../../../packages/foo-package/dev-bar-branch';
```

Tell me if you see something wrong.
Thanks for the feedback @philbates35 ! :+1:

**Comment by philbates35** [comment]
Looks good to me! Let me know when it's available to try out. :+1:

**Comment by Divi** [comment]
Hey @philbates35,

`master` has been updated !
Edit your project `composer.json` :

``` json
{
    "require": {
        "letudiant/composer-shared-package-plugin": "1.1.*@dev"
    },
    "extra": {
        "shared-package": {
            "vendor-dir": "../../packages"
        }
    }
}
```

Then run : `composer update "letudiant/composer-shared-package-plugin"`

Your symlink path should be `../../../../packages/foo-package/dev-bar-branch`.
Waiting for your feedback :ok_hand:

**Comment by philbates35** [comment]
I just tested this out, and yes using the `composer.json` you posted worked exactly as I needed it to. Thanks!

**Comment by Divi** [comment]
Great, I'm glad to hear that. I'll create the stable version tonight.

Thanks @philbates35 :+1:

**Comment by Divi** [comment]
Stable version has been created : https://github.com/Letudiant/composer-shared-package-plugin/tree/1.1.0
