### ISSUE TITLE
Runtime Exception when Scanning for Classes in Vagrant

### ISSUE THREAD

**Issue by timb-pt** [Letudiant/composer-shared-package-plugin#11]
I added the following to an existing composer.json:
```json
{
    "require-dev": {
        "letudiant/composer-shared-package-plugin": "~3.0"
    },
    "extra": {
        "shared-package": {
            "vendor-dir": "/webpt/www/shared-vendor",
            "package-list": [
                "*/*"
            ]
        }
    }
}
```

I ran the following command:
```sh
composer update letudiant/composer-shared-package-plugin
```

... and I got the following results

* Shared folder contains various libraries
* `vendor` folder contains various libraries
* `Generating autoload files` process fails

The output looks like this:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing letudiant/composer-shared-package-plugin (3.1.1)
    Loading from cache

Writing lock file
Generating autoload files


  [RuntimeException]
  Could not scan for classes inside "/vagrant/www/shared-vendor/phpunit/php-token-stream/1.4.8/src/" which does not appear to be a file nor a folder


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

How do I get around this issue, or is there a bugfix needed here?

**Comment by Divi** [comment]
Hello,

Try to delete your `vendor` directory and run a `composer install` command after (or `composer update --lock` if the plugin hasn't installed).  
This error may occur because your vendors are already installed. The plugin cannot determine if the vendor has been shared or not.

After the reinstallation, the autoloader will be rewrited and vendor will be downloaded in the `vendor-shared` directory.

**Comment by timb-pt** [comment]
Thanks, your suggestion (particularly deleting the `vendor` directory) seems to have solved my initial problem.

I encountered another problem that's detailed in #12.
