### ISSUE TITLE
Different branches (require and require-dev)

### ISSUE THREAD

**Issue by pionl** [Letudiant/composer-shared-package-plugin#15]
Hi,
in readme there is mention that in production there can be different branch usage. I've got 2 branches:

- master (for development)
- production (for public)

I've tried setup with:
```
require: "test/test": "dev-production as 1.0",
require-dev: "test/test": "dev-master as 1.0",
```
but exception is raised:
```
The requested package test/test dev-production as 1.0 exists as test/test[dev-master, 1.0] but these are rejected by your constraint. 
```

I've tried also to set:
```
require: "test/test": "dev-production",
require-dev: "test/test": "dev-master as dev-production",
```
this passes but on production it uses the master. I've got lock (want to exact version as I used) from the dev env but I'm trying to update the lock on the CI by calling:
```shell
composer update test/test --no-dev --no-scripts
```

Thanks for any advice.
Have a great day

**Comment by Divi** [comment]
Hello :)

Have you tried like this ?

```
require: "test/test": "~1.0",
require-dev: "test/test": "dev-master as 1.0",
```

Of course, you'll need a tag >= 1.0.0

**Comment by pionl** [comment]
HI @Divi , thanks for the reply. That would probably work, but I need always the latest changes (don't want to create another task to tag every commit), thats why I'm trying to use the production or master branch :)

**Comment by Divi** [comment]
Oh, sorry. Misunderstood.

So just avoid setting the alias `1.0`, like this : 

```
require: "test/test": "dev-production",
require-dev: "test/test": "dev-master"
```

I advice you to switch your branches : a `develop` branch for development purposes and the `master` one for production. It's more logic with the git flow (`master` should be the stable branch).

It will become :

```
require: "test/test": "dev-master",
require-dev: "test/test": "dev-develop"
```

**Comment by Divi** [comment]
Closing this issue, feel free to reopen it if the problem persist.
