### ISSUE TITLE
RuntimeException - Unknown installation source for package

### ISSUE THREAD

**Issue by cuchac** [Letudiant/composer-shared-package-plugin#18]
Hi,

I trigger very often this  exception.

```
[RuntimeException]      
  Unknown installation source for package "composer/ca-bundle" ("1.0.7")
```

It is probably caused by interaction with installed package cache - packages.json. I have several instances of the same project (same name in composer.json project file) sharing same vendor-dir. If all instances use the same package version, everything is OK. After one instance is upgraded, the cache thinks it was the only usage (usage is tracked by package name that is same) and item is removed from packages.json. Next install complains about Unknown installation source for package.

When this error happens, there is no "composer/ca-bundle" inside packages.json cache file even though the package was installed and just get updated.

If I comment-out the place where exception is thrown, everything works OK. It is the workaround I use currently.

**Comment by Divi** [comment]
Hello,

I see, I will force the source tomorrow.
Thanks for the report :)

**Comment by cuchac** [comment]
Hello,
I can provide more detailed information if you have any problem reproducing this issue.
For example minimal script to trigger the exception.

**Comment by Divi** [comment]
Sorry for the delay. It should be fixed with the version `4.0.0`. Don't forget the update your composer.json file.

**Comment by cuchac** [comment]
Thaks! Will update and let you know.

**Comment by cuchac** [comment]
Work like a charm. Thank you very much for such a prompt fix!
