### ISSUE TITLE
symlink contains dev-master, not in the creation path

### ISSUE THREAD

**Issue by xGouley** [Letudiant/composer-shared-package-plugin#8]
When I do a composer install on my project, my shared packages are created in a way the symlink created just after cannot work: 
path to my shared package = '/my-shared-packages/me/package/*'
symlink that points to = '/my-shared-packages/me/package/dev-master/*'

Since the version folder (dev-master) is not here, all my symlinks are broken...

Please help, is it a version/alias problem ?

**Comment by xGouley** [comment]
Can you tell me where is your method that generate the shared path before to let composer write into it?

**Comment by Divi** [comment]
Can you paste me your `composer.json` file please ?

**Comment by xGouley** [comment]
Hi !

I cannot show the project composer.json for now (have to anonymize the content keeping the bug...), but I found the problem : it's a bugged composer version !
With the composer version I had at last week, your plugin works well : https://github.com/composer/composer/commit/a066171dcc023ad6429881a7692e46f10e080f99

But with a selfupdate of composer (tried these for example, including the last version :
https://github.com/composer/composer/commit/f25446e507a3f420b2b88e6dedc47787d42ea7e9
and the today's version: https://github.com/composer/composer/commit/c9501a4cc164b176de48e44b239e619cfd5f14e5
) then your plugin omits the "dev-master" folder in the shared vendor path (not for the symlink creation has I said, just for the path of the shared dependency).

**Comment by xGouley** [comment]
I know there is 3 pages of commits between the version that works and the today's commit... I will be a big diff... but since the last version is KO, maybe the API changed, or the way "getPrettyVersion()" work changed...
If you cannot fix with this, then I will try to anonymize my packag(ist) before to give it to you, next week.

**Comment by Divi** [comment]
Indeed, thanks for the report. The `LibraryInstaller` file has some changes. I must update the plugin. I'll do it as soon as possible :)

**Comment by Divi** [comment]
Update your `composer.json` file with new version of this plugin : `~3.0`, it should be fixed.

**Comment by xGouley** [comment]
I confirm, everything works fine now :) Thank you for your quick fix!
