### ISSUE TITLE
vendor-dir

### ISSUE THREAD

**Issue by babwar** [Letudiant/composer-shared-package-plugin#9]
Hello,

First thanks for this great package. It save me a precious time.
We are some developers with different configuration (os, system file, ..). And the vendor-dir may be different between us. 
So I'm wondering if we could have a system_path (env var path) option in configuration that override vendor-dir.

Excuse for my poor English.
Anyway thanks a lot

**Comment by Divi** [comment]
It's a great idea, I'll do it :+1:

**Comment by Divi** [comment]
Implemented in version `3.1.0`. Please, update your composer by running this command `composer update letudiant/composer-shared-package-plugin`.

See available options documentation for variables name : https://github.com/Letudiant/composer-shared-package-plugin/blob/master/docs/all-available-configurations.md

Thanks @babwar :+1:
